INSERT INTO public.calendar_contents (
  title, 
  description, 
  content_type, 
  maternity_phase, 
  category, 
  content_url, 
  thumbnail_url, 
  duration_minutes, 
  is_premium, 
  baby_age_min_days, 
  baby_age_max_days, 
  day_of_week, 
  week_offset, 
  content_data
) VALUES 
(
  'Mãos que exploram o mundo',
  'Seu bebê começa a abrir as mãos e tocá-las entre si.',
  'tip',
  'newborn',
  'No seu Tempo',
  'https://momwise.app/blog/dia-61',
  NULL,
  3,
  FALSE,
  61,
  61,
  NULL,
  NULL,
  '{"full_content": "Por volta do segundo mês, o bebê começa a abrir mais as mãos e encostar uma na outra. Isso é mais do que fofo — é um marco no desenvolvimento. Ele está descobrindo seu corpo e o espaço ao redor. Hoje, ofereça um brinquedo leve ou um tecido macio para que ele toque, sinta, explore."}'
),
(
  'Hora do banho: um ritual de conexão',
  'Transforme o banho em um momento de presença e vínculo.',
  'article',
  'newborn',
  'Ritmo Leve',
  'https://momwise.app/blog/dia-62',
  NULL,
  4,
  FALSE,
  62,
  62,
  NULL,
  NULL,
  '{"full_content": "Mais do que higiene, o banho pode ser um momento de acolhimento. Água morna, toque atento, voz suave: tudo isso relaxa e comunica amor. Hoje, diminua o ritmo antes do banho. Use a hora como um pequeno ritual, com repetição, previsibilidade e muito olho no olho."}'
),
(
  'Seu bebê está mais alerta',
  'Ele começa a passar mais tempo acordado e observando tudo.',
  'article',
  'newborn',
  'Entendendo o Bebê',
  'https://momwise.app/blog/dia-63',
  NULL,
  3,
  FALSE,
  63,
  63,
  NULL,
  NULL,
  '{"full_content": "Com cerca de dois meses, os períodos de vigília aumentam. Ele já acompanha objetos com o olhar, reage mais à sua voz e se mostra mais ativo. Hoje, aproveite esse tempo para conversar com ele, mostrar cores e movimentos lentos. Cada troca nutre o vínculo e o cérebro em crescimento."}'
),
(
  'Você ainda está no puerpério',
  'Mesmo dois meses depois, seu corpo e emoções seguem se adaptando.',
  'article',
  'newborn',
  'Mãe Inteira',
  'https://momwise.app/blog/dia-64',
  NULL,
  4,
  FALSE,
  64,
  64,
  NULL,
  NULL,
  '{"full_content": "Muita gente acha que o puerpério ''passa'' depois do primeiro mês. Mas ele continua, em ondas. Você ainda está se reorganizando fisicamente, hormonalmente, mentalmente. Hoje, acolha suas oscilações com gentileza. Você está em construção profunda."}'
),
(
  'Amamentação também evolui',
  'Os padrões de mamada mudam ao longo dos meses — e isso é esperado.',
  'article',
  'newborn',
  'Amamentação e Acolhimento',
  'https://momwise.app/blog/dia-65',
  NULL,
  3,
  FALSE,
  65,
  65,
  NULL,
  NULL,
  '{"full_content": "O bebê pode mamar por menos tempo, mas de forma mais eficiente. Ele pode espaçar mamadas ou alternar dias de mais ou menos fome. Isso não significa que algo está errado. Seu corpo e o dele estão se ajustando em harmonia. Hoje, confie no processo — e na sabedoria dos dois."}'
),
(
  'Conversas de corpo inteiro',
  'Ele responde com olhos, expressões e até os pés!',
  'tip',
  'newborn',
  'No seu Tempo',
  'https://momwise.app/blog/dia-66',
  NULL,
  3,
  FALSE,
  66,
  66,
  NULL,
  NULL,
  '{"full_content": "Seu bebê começa a se expressar com o corpo todo: abre os olhos, move braços, franze a testa, agita as pernas. Hoje, experimente falar com ele pausadamente e observe as reações. Isso já é uma conversa. E você está ouvindo com o coração."}'
),
(
  'Rotina ainda é leve, mas existe',
  'Ritualizar horários ajuda o bebê a se orientar no tempo.',
  'article',
  'newborn',
  'Ritmo Leve',
  'https://momwise.app/blog/dia-67',
  NULL,
  4,
  FALSE,
  67,
  67,
  NULL,
  NULL,
  '{"full_content": "Não é preciso rigidez — mas criar pequenas rotinas pode ajudar o bebê a entender o dia. Um banho sempre no fim da tarde, um passeio pela manhã. Esses padrões trazem previsibilidade e conforto. Hoje, escolha um momento do dia e repita com calma. Isso vira memória emocional."}'
),
(
  'Você pode confiar em si mesma',
  'Intuição não é mágica: é conhecimento profundo do vínculo.',
  'article',
  'newborn',
  'Mãe Inteira',
  'https://momwise.app/blog/dia-68',
  NULL,
  4,
  FALSE,
  68,
  68,
  NULL,
  NULL,
  '{"full_content": "Talvez você já perceba que, mesmo sem ler nada, sabe o que o bebê precisa. Essa é sua intuição sendo refinada pela experiência. Hoje, confie em um palpite seu. Mesmo que não seja ''perfeito'', ele parte do lugar certo: do vínculo real entre vocês dois."}'
),
(
  'A higiene pode ser natural',
  'Observar os sinais do bebê é um caminho gentil e possível.',
  'article',
  'newborn',
  'Higiene Natural',
  'https://momwise.app/blog/dia-69',
  NULL,
  3,
  FALSE,
  69,
  69,
  NULL,
  NULL,
  '{"full_content": "Mesmo pequenos, muitos bebês demonstram desconforto ao urinar ou evacuar. A higiene natural se baseia na observação desses sinais e no respeito ao ritmo do bebê. Hoje, ao trocar a fralda, observe as expressões antes e depois. Só isso já é um começo gentil para esse caminho."}'
),
(
  'Trocas com outras mães curam',
  'Falar, ouvir, rir, desabafar — tudo isso fortalece.',
  'article',
  'newborn',
  'Entre Mães',
  'https://momwise.app/blog/dia-70',
  NULL,
  4,
  FALSE,
  70,
  70,
  NULL,
  NULL,
  '{"full_content": "Nada substitui a escuta de outra mulher que está passando pelo mesmo. Hoje, envie uma mensagem sincera para uma mãe que você admira. Ou escreva num grupo, com verdade. O apoio entre mães sustenta mais do que conselhos."}'
);