-- Inserir conteúdo personalizado do calendário para recém-nascidos
INSERT INTO public.calendar_contents (
  title, description, content_type, maternity_phase, category, content_url, 
  thumbnail_url, duration_minutes, is_premium, baby_age_min_days, baby_age_max_days, 
  day_of_week, week_offset, content_data
) VALUES 
('Primeiro colo, primeira conexão', 'O bebê nasceu e precisa sentir que está seguro no seu cheiro, voz e pele.', 'article', 'newborn', 'Amamentação e Acolhimento', 'https://momwise.app/blog/dia-1', NULL, 4, FALSE, 0, 0, NULL, NULL, '{"full_content": "Hoje começa sua jornada como mãe. Seu bebê não enxerga muito, mas reconhece sua voz, cheiro e toque. Ele precisa se sentir seguro. A primeira hora de vida é chamada de ''hora de ouro'' porque fortalece o vínculo e favorece o início da amamentação. Não se preocupe com regras ou expectativas. Apenas sinta. Hoje, fique pele a pele com seu bebê por pelo menos 20 minutos. Respire com ele."}'),

('Seu corpo sabe o que fazer', 'O colostro é tudo o que seu bebê precisa agora. Confie: seu corpo é sábio.', 'article', 'newborn', 'Amamentação e Acolhimento', 'https://momwise.app/blog/dia-2', NULL, 4, FALSE, 1, 1, NULL, NULL, '{"full_content": "O colostro é o primeiro leite e é riquíssimo em anticorpos. Pequenas quantidades são suficientes para alimentar seu bebê. Cada mamada ajuda o corpo a entender o quanto deve produzir. O leite maduro chegará em breve, e até lá, a sucção do bebê será sua melhor aliada. Hoje, amamente em livre demanda, sem relógio. Seu corpo está fazendo o que precisa. Confie nele."}'),

('Choro é comunicação, não manipulação', 'O choro do bebê é linguagem. Ele ainda não tem outra forma de se expressar.', 'article', 'newborn', 'Sono do Bebê', 'https://momwise.app/blog/dia-3', NULL, 3, FALSE, 2, 2, NULL, NULL, '{"full_content": "Chorar é a forma mais primitiva e eficaz de um bebê se comunicar. Ele pode estar com fome, desconforto, sono, ou apenas querendo colo. Responder ao choro com presença ensina segurança emocional. Não se trata de mimar, mas de formar vínculo e confiança. Hoje, tente acolher o choro com calma. Respire fundo antes de agir. O bebê sente sua presença mais do que qualquer solução imediata."}'),

('Cuidando do umbiguinho', 'O coto umbilical precisa de pouco: apenas ar, limpeza e paciência.', 'tip', 'newborn', 'Higiene Natural', 'https://momwise.app/blog/dia-4', NULL, 2, FALSE, 3, 3, NULL, NULL, '{"full_content": "O coto umbilical costuma cair entre 5 e 15 dias. Não é necessário usar medicamentos ou faixas. Mantenha a região seca e limpa. Se houver sangue seco, use uma gaze com soro fisiológico para limpar com delicadeza. Evite cobrir com a fralda — dobre a borda para baixo. Se notar cheiro forte, secreção amarela ou vermelhidão, procure orientação médica."}'),

('Shantala: o toque que acolhe', 'A Shantala promove vínculo, alivia cólicas e acalma o bebê.', 'activity', 'newborn', 'No seu Tempo', 'https://momwise.app/blog/dia-5', NULL, 5, FALSE, 4, 4, NULL, NULL, '{"full_content": "A massagem Shantala é um presente ancestral que você pode oferecer ao seu bebê. Com um pouco de óleo vegetal e um ambiente aquecido, você conduz toques suaves e repetitivos nos braços, pernas e barriga. Isso alivia gases, estimula o sistema nervoso e cria vínculo profundo. Hoje, experimente fazer 5 minutos de massagem antes do banho. Respirem juntos. Essa troca vale mais do que mil palavras."}'),

('Leite maduro chegando', 'O volume aumenta, os seios pesam, o bebê mama mais — tudo isso é esperado.', 'article', 'newborn', 'Amamentação e Acolhimento', 'https://momwise.app/blog/dia-6', NULL, 4, FALSE, 5, 5, NULL, NULL, '{"full_content": "O colostro está dando lugar ao leite maduro. Isso significa aumento no volume, seios mais pesados e bebês mamando com mais frequência. Pode haver algum desconforto, mas é sinal de que o corpo está entendendo o ritmo do bebê. Hoje, tente fazer compressas mornas antes das mamadas e frias após. Isso ajuda na descida do leite e alivia a tensão nas mamas."}'),

('Você é o mundo dele', 'Seu bebê está se adaptando a tudo: luz, temperatura, sons. E você é o porto seguro.', 'article', 'newborn', 'Mãe Inteira', 'https://momwise.app/blog/dia-7', NULL, 3, FALSE, 6, 6, NULL, NULL, '{"full_content": "O bebê está vivendo sua primeira semana fora do útero. Cada som, toque e cheiro é novo. E é você quem organiza esse mundo para ele. Mesmo sem rotina, seus braços são o lugar mais conhecido que ele tem. Hoje, abrace, fale com calma e apenas esteja junto. Não se cobre produtividade. Você está fundando uma nova existência. Isso já é tudo."}'),

('Transição do útero para o mundo', 'Recriar sensações uterinas ajuda o bebê a se sentir seguro.', 'tip', 'newborn', 'Sono do Bebê', 'https://momwise.app/blog/dia-8', NULL, 3, FALSE, 7, 7, NULL, NULL, '{"full_content": "Nos primeiros dias, o bebê se sente melhor quando as sensações do útero são parcialmente recriadas: contenção, calor, som do coração. Hoje, tente embalar o bebê com movimentos suaves, usar um sling ou ruído branco, e deixá-lo próximo ao seu peito. Esse cuidado não é excesso, é necessidade. Ajuda o bebê a fazer uma transição mais suave para o mundo."}'),

('Mãos à boca: é fome?', 'Nem sempre. Às vezes, é só conforto. Aprenda a observar com carinho.', 'tip', 'newborn', 'No seu Tempo', 'https://momwise.app/blog/dia-9', NULL, 3, FALSE, 8, 8, NULL, NULL, '{"full_content": "Levar as mãos à boca pode significar fome, sim — mas também é um reflexo natural e uma forma de se acalmar. Observar o contexto é essencial. Acabou de mamar? Está sonolento? Está fazendo isso com frequência? Hoje, pratique observar antes de agir. Conhecer os sinais do seu bebê é uma dança que se aprende com tempo e presença."}'),

('Seu bebê já sabe muito', 'Mesmo tão pequeno, ele já reconhece padrões, vozes e emoções.', 'article', 'newborn', 'No seu Tempo', 'https://momwise.app/blog/dia-10', NULL, 4, FALSE, 9, 9, NULL, NULL, '{"full_content": "O cérebro do bebê está se desenvolvendo rapidamente. Mesmo com poucos dias de vida, ele já reconhece o som da sua voz, sua pele, seu cheiro. Ele distingue ritmos e reage a expressões faciais. Cada troca é uma aula para ele — e você é a professora mais importante. Hoje, olhe nos olhos dele durante o banho ou mamada. Faça expressões, sons, chame pelo nome. Isso nutre vínculo e inteligência ao mesmo tempo."}'),

('Você ainda é você', 'A maternidade transforma, mas não apaga quem você era antes.', 'article', 'newborn', 'Mãe Inteira', 'https://momwise.app/blog/dia-11', NULL, 4, FALSE, 10, 10, NULL, NULL, '{"full_content": "Entre fraldas e mamadas, é fácil esquecer de si mesma. Mas a mulher que você era antes da maternidade ainda vive aí dentro. Ela só está se transformando. Hoje, tente lembrar de algo que você gostava de fazer antes do bebê. Um chá preferido, uma música, uma leitura. Você não precisa tentar voltar a ser quem era. Mas pode se reconectar com pedaços seus que continuam vivos, mesmo sob novas formas."}'),

('Banho de sol e vitamina D', 'Um pouco de sol da manhã ajuda a saúde do bebê e também o seu bem-estar.', 'tip', 'newborn', 'Higiene Natural', 'https://momwise.app/blog/dia-12', NULL, 3, FALSE, 11, 11, NULL, NULL, '{"full_content": "A luz do sol das primeiras horas da manhã é uma fonte natural de vitamina D. Essa exposição breve e indireta fortalece ossos e imunidade. Para o bebê, 5 a 10 minutos de sol nas pernas e braços já são suficientes. Para você, a luz matinal regula o ciclo circadiano e ajuda até na produção de leite. Hoje, se possível, abra a janela ou vá até um cantinho iluminado. O sol é cura ancestral."}'),

('Peça ajuda – e aceite', 'Pedir ajuda não te enfraquece. Te sustenta.', 'article', 'newborn', 'Entre Mães', 'https://momwise.app/blog/dia-13', NULL, 4, FALSE, 12, 12, NULL, NULL, '{"full_content": "Existe uma ideia equivocada de que uma mãe forte dá conta de tudo sozinha. Mas a força real está em saber quando pedir apoio. Família, amigos, vizinhos – alguém pode te trazer uma refeição, segurar o bebê por 15 minutos ou apenas ouvir você. Hoje, escolha uma pequena tarefa que você pode delegar. Abrir espaço para ajuda é um gesto de amor próprio e de saúde mental."}'),

('A força da sua voz', 'Seu bebê reconhece sua voz desde o útero. Agora ela acalma, orienta e encanta.', 'tip', 'newborn', 'No seu Tempo', 'https://momwise.app/blog/dia-14', NULL, 3, FALSE, 13, 13, NULL, NULL, '{"full_content": "A fala da mãe é um dos sons mais reguladores para o bebê. Mesmo que ele ainda não entenda as palavras, reconhece o tom, o ritmo e a emoção. Hoje, converse com seu bebê durante o banho, a troca de fralda ou a mamada. Narre o que está acontecendo com calma. Cantar também é poderoso. Sua voz é familiar, única e profundamente segura para ele."}'),

('Sua cicatrização é sagrada', 'O corpo ainda está se refazendo. Honre seu tempo interno.', 'article', 'newborn', 'Mãe Inteira', 'https://momwise.app/blog/dia-15', NULL, 4, FALSE, 14, 14, NULL, NULL, '{"full_content": "Mesmo que por fora tudo pareça em ordem, seu corpo ainda está em processo profundo de reorganização. O útero está voltando ao tamanho original, os hormônios se reequilibrando, e seu emocional se adaptando. Respeite o cansaço. Evite sobrecargas. Hoje, coloque as pernas para cima por 10 minutos, beba água morna com limão ou apenas se permita descansar mais. Você está se recuperando e ao mesmo tempo nutrindo outra vida."}'),

('Sua voz é abrigo', 'Mesmo sem entender palavras, o bebê reconhece sua voz como segurança.', 'tip', 'newborn', 'Amamentação e Acolhimento', 'https://momwise.app/blog/dia-16', NULL, 3, FALSE, 15, 15, NULL, NULL, '{"full_content": "Mesmo antes de nascer, o bebê já ouvia sua voz. Agora, ela é abrigo. Falar com ele é como costurar afeto nos pequenos gestos do dia. Durante as mamadas, trocas ou momentos de colo, converse. Não importa o que diga — o som é o que acolhe. Hoje, experimente cantar uma canção de ninar criada por você. Ele só precisa ouvir que você está aí."}'),

('O bebê ainda não sabe esperar', 'Chorar é o único jeito que ele tem de pedir ajuda — e tudo é urgente para ele.', 'article', 'newborn', 'Sono do Bebê', 'https://momwise.app/blog/dia-17', NULL, 4, FALSE, 16, 16, NULL, NULL, '{"full_content": "O conceito de ''esperar'' não existe para um recém-nascido. Para ele, o tempo não é linear — é só sensação. Se está com fome, quer agora. Se precisa de colo, é agora. Quando atendemos prontamente, ele aprende que o mundo é seguro. Hoje, tente observar como seu bebê responde quando é acolhido rapidamente. Esse cuidado forma as raízes da confiança."}'),

('Respire com ele', 'O toque e a respiração juntos são poderosos reguladores para o bebê.', 'activity', 'newborn', 'No seu Tempo', 'https://momwise.app/blog/dia-18', NULL, 5, FALSE, 17, 17, NULL, NULL, '{"full_content": "Quando você segura o bebê no colo, o corpo dele se molda ao seu. O mesmo acontece com a respiração. Se você respira devagar e profundamente, o bebê sente e regula junto. Hoje, deite-se com ele em seu peito, em silêncio, e respirem juntos por alguns minutos. Não é técnica. É presença pura."}'),

('Rotina ainda não existe — e tudo bem', 'É normal que os dias ainda pareçam bagunçados. O bebê ainda vive por instinto.', 'article', 'newborn', 'Sono do Bebê', 'https://momwise.app/blog/dia-19', NULL, 4, FALSE, 18, 18, NULL, NULL, '{"full_content": "Muitos pais se preocupam em criar uma rotina desde o início. Mas nas primeiras semanas, o bebê ainda funciona por necessidade e instinto. Sono, mamada, colo, tudo acontece de forma orgânica, não organizada. Isso é saudável. Hoje, observe os ciclos do seu bebê sem tentar mudar. Apenas anote os horários para conhecer o ritmo que ele está construindo com você."}'),

('Seu cuidado vale ouro', 'Você está fazendo muito mais do que parece. O invisível também importa.', 'article', 'newborn', 'Mãe Inteira', 'https://momwise.app/blog/dia-20', NULL, 4, FALSE, 19, 19, NULL, NULL, '{"full_content": "O que você faz, mesmo que ninguém veja, tem impacto profundo: embalar, dar de mamar, acolher o choro. Esses gestos são a base da segurança emocional do seu bebê. Mesmo sem glamour, são atos de amor potentes. Hoje, olhe para si com mais gentileza. Anote três coisas que você fez hoje que nutrem seu bebê — mesmo que pareçam pequenas. Elas são gigantes."}');