INSERT INTO public.calendar_contents (
  title, 
  description, 
  content_type, 
  maternity_phase, 
  category, 
  content_url, 
  thumbnail_url, 
  duration_minutes, 
  is_premium, 
  baby_age_min_days, 
  baby_age_max_days, 
  day_of_week, 
  week_offset, 
  content_data
) VALUES 
(
  'Ritual da noite: banho morno com afeto',
  'Um banho calmo à noite pode ajudar o bebê a adormecer melhor.',
  'tip',
  'newborn',
  'Sono do Bebê',
  'https://momwise.app/blog/dia-21',
  NULL,
  3,
  FALSE,
  20,
  20,
  NULL,
  NULL,
  '{"full_content": "Criar um ritual de sono, mesmo simples, ajuda o bebê a reconhecer que está na hora de dormir. Um banho morno, luz baixa e uma música suave criam um ambiente de transição. Hoje, experimente oferecer esse momento com presença e sem pressa. Seu bebê vai sentir o acolhimento e relaxar mais profundamente."}'
),
(
  'Toque que fortalece: massagem nos pezinhos',
  'A massagem nos pés ajuda a relaxar e melhora a circulação.',
  'tip',
  'newborn',
  'No seu Tempo',
  'https://momwise.app/blog/dia-22',
  NULL,
  3,
  FALSE,
  21,
  21,
  NULL,
  NULL,
  '{"full_content": "Toques suaves nos pés do bebê não apenas relaxam, como estimulam o sistema nervoso e circulatório. Use óleo vegetal ou simplesmente suas mãos mornas. Faça movimentos circulares nas solas, nos dedinhos e nos calcanhares. Esse contato cria vínculo, segurança e conexão. Hoje, pratique esse toque com intenção de presença."}'
),
(
  'Seu bebê sente o seu olhar',
  'O olhar da mãe é nutriente emocional para o bebê.',
  'article',
  'newborn',
  'Entre Mães',
  'https://momwise.app/blog/dia-23',
  NULL,
  4,
  FALSE,
  22,
  22,
  NULL,
  NULL,
  '{"full_content": "O contato visual entre mãe e bebê ativa áreas do cérebro ligadas ao afeto, à linguagem e à segurança. Mesmo que ele ainda não fixe por muito tempo, o bebê busca o seu olhar. Hoje, reserve alguns minutos para apenas olhar nos olhos dele enquanto conversa suavemente. É mais poderoso do que parece."}'
),
(
  'A amamentação também é emocional',
  'O peito é aconchego, e não apenas alimento.',
  'article',
  'newborn',
  'Amamentação e Acolhimento',
  'https://momwise.app/blog/dia-24',
  NULL,
  4,
  FALSE,
  23,
  23,
  NULL,
  NULL,
  '{"full_content": "O bebê busca o peito não só por fome, mas por conforto, cheiro, calor, e para regular emoções. Esse uso afetivo do seio é normal e desejável. Hoje, se o bebê quiser mamar de novo e de novo, acolha com calma. Ele está organizando suas emoções através da sua presença física e do seu leite."}'
),
(
  'Você está mais forte do que imagina',
  'Mesmo cansada, você segue — isso é força.',
  'article',
  'newborn',
  'Mãe Inteira',
  'https://momwise.app/blog/dia-25',
  NULL,
  3,
  FALSE,
  24,
  24,
  NULL,
  NULL,
  '{"full_content": "A maternidade exige uma força nova: silenciosa, persistente, emocional. Você talvez não perceba, mas está atravessando noites em claro, dores físicas e transformações imensas com coragem. Hoje, olhe para si com gentileza. A força da mãe não está no controle, mas na entrega diária — mesmo nas falhas."}'
),
(
  'Você não precisa dar conta de tudo',
  'Pedir ajuda também é um ato de amor com seu bebê.',
  'article',
  'newborn',
  'Mãe Inteira',
  'https://momwise.app/blog/dia-26',
  NULL,
  4,
  FALSE,
  25,
  25,
  NULL,
  NULL,
  '{"full_content": "Existe uma idealização de que a mãe deve dar conta de tudo sozinha. Mas a maternidade é, por natureza, um trabalho coletivo. Pedir ajuda, dividir tarefas e aceitar apoio são formas de cuidar melhor — de si e do bebê. Hoje, veja se há algo que você pode delegar ou dividir. Você merece também ser cuidada."}'
),
(
  'A primeira vocalização',
  'Aos poucos, o bebê começa a emitir sons diferentes do choro.',
  'tip',
  'newborn',
  'Entendendo o Bebê',
  'https://momwise.app/blog/dia-27',
  NULL,
  3,
  FALSE,
  26,
  26,
  NULL,
  NULL,
  '{"full_content": "Você pode começar a notar sons como ''ah'', ''gu'', ''eh'' saindo da boca do seu bebê. São as primeiras vocalizações intencionais, sinais de que ele está testando a própria voz. Responda com entusiasmo, repita os sons. Essa troca fortalece a linguagem e o vínculo afetivo. Hoje, escute e converse com seu bebê — mesmo que ainda pareça uma conversa de um só lado."}'
),
(
  'Shantala: carinho em movimento',
  'A massagem Shantala é uma forma ancestral de criar conexão com o bebê.',
  'article',
  'newborn',
  'No seu Tempo',
  'https://momwise.app/blog/dia-28',
  NULL,
  4,
  FALSE,
  27,
  27,
  NULL,
  NULL,
  '{"full_content": "A prática da Shantala envolve movimentos lentos e ritmados com óleo vegetal no corpo do bebê. Além de relaxar, ajuda na digestão, no sono e na consciência corporal. Hoje, experimente aprender alguns movimentos básicos. Não precisa ser perfeito — o que importa é o toque com intenção e presença."}'
),
(
  'Quando o peito vira ninho',
  'Mesmo que o bebê não sugue, o contato com o seio ainda é valioso.',
  'tip',
  'newborn',
  'Amamentação e Acolhimento',
  'https://momwise.app/blog/dia-29',
  NULL,
  3,
  FALSE,
  28,
  28,
  NULL,
  NULL,
  '{"full_content": "Às vezes o bebê quer o peito, mas não está com fome. Ele apenas encosta, chupa sem sugar ou dorme ali. Esse é um uso emocional do seio, e é tão importante quanto o nutritivo. Hoje, acolha esse momento com menos pressa. Seu peito está sendo casa, refúgio, contenção."}'
),
(
  'Seu bebê já reconhece o ambiente',
  'Ele sabe quando está em casa, no colo certo ou em um lugar novo.',
  'article',
  'newborn',
  'Entendendo o Bebê',
  'https://momwise.app/blog/dia-30',
  NULL,
  3,
  FALSE,
  29,
  29,
  NULL,
  NULL,
  '{"full_content": "Mesmo com apenas um mês de vida, seu bebê já percebe mudanças de ambiente, vozes familiares e a energia do entorno. Por isso ele pode se acalmar mais no seu colo, ou estranhar uma visita barulhenta. Hoje, ofereça momentos tranquilos no ambiente conhecido. Isso fortalece a noção de segurança e pertencimento."}'
),
(
  'Seu bebê já sorri?',
  'Por volta das 6 semanas, muitos bebês oferecem seu primeiro sorriso social.',
  'article',
  'newborn',
  'Entendendo o Bebê',
  'https://momwise.app/blog/dia-31',
  NULL,
  4,
  FALSE,
  30,
  30,
  NULL,
  NULL,
  '{"full_content": "Até aqui, os sorrisos do bebê eram reflexos. Agora, por volta da 6ª semana, ele pode sorrir como resposta ao seu rosto, voz ou toque. Esse sorriso é uma conquista — do bebê e sua. Ele mostra que a comunicação afetiva está funcionando. Hoje, brinque de fazer caretas, sons engraçados, sorrir. Mesmo que ele ainda não sorria de volta, ele está aprendendo o caminho do afeto."}'
),
(
  'Cuidar de você também é cuidar dele',
  'Seu bem-estar físico e emocional influencia diretamente o do bebê.',
  'article',
  'newborn',
  'Mãe Inteira',
  'https://momwise.app/blog/dia-32',
  NULL,
  4,
  FALSE,
  31,
  31,
  NULL,
  NULL,
  '{"full_content": "Muitas mães sentem culpa por quererem tempo para si mesmas. Mas esse desejo é saudável. Quando você se alimenta bem, dorme um pouco, respira com calma, você oferece mais presença para o bebê. Hoje, tente fazer algo só por você: um banho mais demorado, 10 minutos de sol, um chá quente. Você também precisa ser nutrida."}'
),
(
  'Ruído branco: o som do útero',
  'Ruído branco lembra o som intrauterino e ajuda a acalmar o bebê.',
  'tip',
  'newborn',
  'Sono do Bebê',
  'https://momwise.app/blog/dia-33',
  NULL,
  3,
  FALSE,
  32,
  32,
  NULL,
  NULL,
  '{"full_content": "Durante a gestação, o bebê ouvia um mundo de sons abafados: seu coração, intestinos, o fluxo do sangue. Após o nascimento, o silêncio total pode causar estranhamento. Por isso o ruído branco funciona tão bem. Hoje, tente colocar um som de secador, ventilador ou chuva suave quando o bebê estiver inquieto. Pode ajudar a acalmá-lo no sono e na cólica."}'
),
(
  'Bebê que mama muito não é guloso',
  'Ele está apenas seguindo sua natureza e regulando necessidades variadas.',
  'article',
  'newborn',
  'Amamentação e Acolhimento',
  'https://momwise.app/blog/dia-34',
  NULL,
  3,
  FALSE,
  33,
  33,
  NULL,
  NULL,
  '{"full_content": "Um bebê que quer mamar o tempo todo está sendo... um bebê. O peito não é só alimento, é também regulação emocional, segurança, temperatura, conforto. Hoje, abrace a livre demanda como uma dança entre vocês. Se está difícil, peça ajuda — você não precisa dar conta de tudo sozinha."}'
),
(
  'Movimentos com propósito',
  'Seu bebê começa a descobrir que pode mexer braços e pernas com intenção.',
  'tip',
  'newborn',
  'No seu Tempo',
  'https://momwise.app/blog/dia-35',
  NULL,
  3,
  FALSE,
  34,
  34,
  NULL,
  NULL,
  '{"full_content": "Ao longo da 6ª semana, os movimentos do bebê deixam de ser totalmente reflexos e começam a ser mais coordenados. Ele pode mexer braços e pernas com intenção, virar a cabeça para procurar som ou luz. Hoje, deite o bebê de barriga para cima e observe. Mexa um brinquedo de pano perto dos pés e veja como ele responde com alegria."}'
),
(
  'O amor é um ninho',
  'A sensação de ninho acolhe, acalma e estrutura o bebê emocionalmente.',
  'article',
  'newborn',
  'Entre Mães',
  'https://momwise.app/blog/dia-36',
  NULL,
  3,
  FALSE,
  35,
  35,
  NULL,
  NULL,
  '{"full_content": "Quando você embala seu bebê, ele sente que existe um lugar seguro no mundo. Seu colo é ninho, seu toque acalenta. Não existe excesso de cuidado nos primeiros meses. O que há é construção de segurança. Hoje, sinta orgulho por cada vez que atendeu seu bebê com presença. Você está criando raízes internas que ele levará por toda a vida."}'
),
(
  'Seu leite muda com o tempo',
  'A composição do leite materno se adapta às necessidades do bebê.',
  'article',
  'newborn',
  'Amamentação e Acolhimento',
  'https://momwise.app/blog/dia-37',
  NULL,
  4,
  FALSE,
  36,
  36,
  NULL,
  NULL,
  '{"full_content": "O leite que seu corpo produz hoje não é o mesmo de quando o bebê nasceu. Ele muda de acordo com a fase, hora do dia, clima e até se o bebê está doente. De manhã é mais aguado e refrescante. À noite, mais gorduroso e indutor do sono. Hoje, confie no seu corpo. Ele está fazendo exatamente o que o seu bebê precisa — inclusive quando ele mama o tempo todo."}'
),
(
  'Contato pele a pele ainda faz diferença',
  'Mesmo com semanas de vida, o bebê se beneficia imensamente desse gesto.',
  'tip',
  'newborn',
  'Amamentação e Acolhimento',
  'https://momwise.app/blog/dia-38',
  NULL,
  3,
  FALSE,
  37,
  37,
  NULL,
  NULL,
  '{"full_content": "O contato pele a pele regula os batimentos cardíacos do bebê, a temperatura e os níveis de cortisol. Mesmo após o primeiro mês, ele ainda precisa desse aconchego íntimo. Hoje, tire uns minutos para ficar com ele de fralda no seu colo, pele com pele, em silêncio ou ouvindo música calma. Essa troca é nutritiva para ambos."}'
),
(
  'Seu bebê tem memória emocional',
  'Ele pode não lembrar, mas sente e registra tudo em sua história corporal.',
  'article',
  'newborn',
  'Entendendo o Bebê',
  'https://momwise.app/blog/dia-39',
  NULL,
  4,
  FALSE,
  38,
  38,
  NULL,
  NULL,
  '{"full_content": "O bebê não tem memória lógica, mas já constrói uma memória emocional. Ele aprende se o mundo é um lugar seguro a partir das respostas que recebe: ao choro, ao toque, ao sono. Hoje, confie que cada resposta sua está moldando o coração dele. Mesmo em silêncio, o cuidado está sendo absorvido."}'
),
(
  'Você também renasce',
  'Não é só o bebê que nasceu — você também está sendo reconstruída.',
  'article',
  'newborn',
  'Mãe Inteira',
  'https://momwise.app/blog/dia-40',
  NULL,
  4,
  FALSE,
  39,
  39,
  NULL,
  NULL,
  '{"full_content": "Na maternidade, você não volta a ser quem era. E tudo bem. Você está construindo uma nova identidade, com novas prioridades, novos sonhos, nova força. Hoje, olhe para uma foto sua de antes da maternidade e se acolha. Você está renascendo também. E isso leva tempo, coragem e muito amor."}'
);