INSERT INTO public.calendar_contents (
  title, 
  description, 
  content_type, 
  maternity_phase, 
  category, 
  content_url, 
  thumbnail_url, 
  duration_minutes, 
  is_premium, 
  baby_age_min_days, 
  baby_age_max_days, 
  day_of_week, 
  week_offset, 
  content_data
) VALUES 
(
  'Sinais de sono: observe o corpo',
  'Antes do choro, o corpo do bebê já dá sinais de cansaço.',
  'tip',
  'newborn',
  'Sono do Bebê',
  'https://momwise.app/blog/dia-51',
  NULL,
  3,
  FALSE,
  50,
  50,
  NULL,
  NULL,
  '{"full_content": "Bocejos, esfregar os olhos, olhar perdido, movimentos mais lentos — esses são sinais precoces de sono. Muitos bebês choram não por sono em si, mas por estarem passando do ponto de descanso. Hoje, tente observar os sinais antes do choro. Prepare um ambiente calmo, com pouca luz, e ajude seu bebê a adormecer mais tranquilo. Vale a pena testar uma luz vermelha ao invés da luz branca. Ela acalma o bebê e ainda ilumina o ambiente."}'
),
(
  'Seu bebê aprende pelo corpo',
  'Movimento é desenvolvimento — mesmo nos primeiros meses.',
  'article',
  'newborn',
  'No seu Tempo',
  'https://momwise.app/blog/dia-52',
  NULL,
  4,
  FALSE,
  51,
  51,
  NULL,
  NULL,
  '{"full_content": "Deitar de barriga para cima, tocar o próprio corpo, explorar o espaço com o olhar — tudo isso já é estímulo. Não há pressa em alcançar marcos motores. O mais importante é permitir que o bebê tenha tempo e espaço para se mover com liberdade. Hoje, estenda um pano no chão e deite o bebê sem distrações. Observe o que ele descobre com o próprio corpo."}'
),
(
  'Picos de crescimento existem',
  'O bebê pode parecer ''grudado'' por dias — é um sinal de que está crescendo.',
  'article',
  'newborn',
  'Amamentação e Acolhimento',
  'https://momwise.app/blog/dia-53',
  NULL,
  4,
  FALSE,
  52,
  52,
  NULL,
  NULL,
  '{"full_content": "Entre a 7ª e 8ª semana, muitos bebês passam por um pico de crescimento. Eles mamam com mais frequência, acordam mais à noite e pedem mais colo. Essa fase pode durar de 2 a 3 dias ou até mais de uma semana. É intensa, mas passageira. Hoje, acolha com mais colo e menos cobrança. Seu bebê está crescendo e isso exige mais do corpo — e do seu também."}'
),
(
  'Você está presente. E isso basta.',
  'Mãe suficiente não é a perfeita — é a disponível com amor e intenção.',
  'article',
  'newborn',
  'Mãe Inteira',
  'https://momwise.app/blog/dia-54',
  NULL,
  4,
  FALSE,
  53,
  53,
  NULL,
  NULL,
  '{"full_content": "Você não precisa entreter, estimular ou acalmar o tempo todo. Estar com o bebê, com presença genuína, já é nutrir. Bebês não exigem mães perfeitas, mas mães que respondem, que olham nos olhos, que acolhem o que é possível naquele dia. Hoje, abrace essa presença imperfeita com compaixão. Você está fazendo um lindo trabalho."}'
),
(
  'Hora de olhar para o puerpério',
  'Você também está passando por um intenso processo de adaptação.',
  'article',
  'newborn',
  'Mãe Inteira',
  'https://momwise.app/blog/dia-55',
  NULL,
  4,
  FALSE,
  54,
  54,
  NULL,
  NULL,
  '{"full_content": "O puerpério é mais do que um período após o parto. É um mergulho profundo em transformações físicas, hormonais, emocionais e sociais. Você está se adaptando a um novo corpo, novas rotinas e a uma nova identidade. Hoje, valide tudo o que sente — mesmo as emoções ambíguas. Falar, escrever ou acolher essas sensações é parte da cura."}'
),
(
  'Por que ele chora mais ao fim do dia?',
  'Final do dia pode trazer sobrecarga sensorial — e o choro ajuda a descarregar.',
  'article',
  'newborn',
  'Entendendo o Bebê',
  'https://momwise.app/blog/dia-56',
  NULL,
  4,
  FALSE,
  55,
  55,
  NULL,
  NULL,
  '{"full_content": "É comum que bebês fiquem mais irritados no final da tarde. Isso acontece porque, ao longo do dia, eles absorvem estímulos diversos e não sabem como descarregar. O choro, nesse momento, funciona como um ''reset''. Hoje, tente diminuir o ritmo da casa no fim da tarde: evite barulho, luz forte e muitas interações. Um banho morno e contato pele a pele podem ajudar muito."}'
),
(
  'Seu bebê reconhece padrões',
  'Mesmo sem perceber, você já está criando uma rotina afetiva.',
  'tip',
  'newborn',
  'Ritmo Leve',
  'https://momwise.app/blog/dia-57',
  NULL,
  3,
  FALSE,
  56,
  56,
  NULL,
  NULL,
  '{"full_content": "Repetir pequenos gestos diariamente — como o banho em determinado horário ou a canção antes da mamada noturna — ajuda o bebê a prever o que vem a seguir. Esses micro-rituais são as primeiras estruturas de tempo que ele entende. Hoje, observe quais rituais já existem sem intenção. Você pode reforçá-los com afeto e presença, e isso criará segurança emocional."}'
),
(
  'Você está se afinando com ele',
  'Quanto mais o conhece, mais você sente antes mesmo de entender.',
  'article',
  'newborn',
  'Entre Mães',
  'https://momwise.app/blog/dia-58',
  NULL,
  3,
  FALSE,
  57,
  57,
  NULL,
  NULL,
  '{"full_content": "A maternidade afina a percepção: você percebe o choro antes que ele aconteça, reconhece o olhar de fome, sente no seu corpo o que o bebê precisa. Isso não vem de manuais, vem da convivência diária. Hoje, celebre o quanto já aprendeu — mesmo sem se dar conta. Você está se tornando especialista nesse bebê único."}'
),
(
  'Choro não é fracasso',
  'É comunicação. E você não precisa impedir, mas acolher.',
  'article',
  'newborn',
  'Amamentação e Acolhimento',
  'https://momwise.app/blog/dia-59',
  NULL,
  4,
  FALSE,
  58,
  58,
  NULL,
  NULL,
  '{"full_content": "Muitas mães associam o choro a erro ou inadequação. Mas o choro é a principal linguagem do bebê. Nem sempre você vai conseguir acalmar imediatamente — e isso não significa que falhou. Hoje, escute o choro com o coração aberto. Acolher com presença, sem pressa, já é consolo."}'
),
(
  'Seu colo é casa',
  'Para o bebê, estar no seu corpo é estar em segurança.',
  'article',
  'newborn',
  'Amamentação e Acolhimento',
  'https://momwise.app/blog/dia-60',
  NULL,
  4,
  FALSE,
  59,
  59,
  NULL,
  NULL,
  '{"full_content": "Seu corpo ainda é a principal referência de segurança para o bebê. Ele se acalma com seu cheiro, temperatura, movimento. Não é mimo. É biologia. É vínculo. Hoje, carregue-o no colo sem culpa. Seu corpo está fazendo o trabalho mais importante do mundo: ser ninho, ser casa, ser presença viva."}'
);