// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gchbbgytnotdvfvwikwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjaGJiZ3l0bm90ZHZmdndpa3d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NDU1MjksImV4cCI6MjA2ODMyMTUyOX0.MM_Tmi2YoFZdBx5gDLASjrq9bSRxI5aI6yLa_BvBtfI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});